### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: 'boolean org.bukkit.inventory.meta.ItemMeta.hasTool()'

### ISSUE THREAD

**Issue by Yiiitt** [oraxen/oraxen#1591]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[03:59:05 INFO]: [Oraxen] Enabling Oraxen v1.185.0
[03:59:05 INFO]: Oraxen | Version v1_20_R4 has been detected.
[03:59:05 INFO]: Oraxen | Oraxen will use the NMSHandler for this version.
[03:59:06 ERROR]: Error occurred while enabling Oraxen v1.185.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.inventory.meta.ItemMeta.hasTool()'
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.items.ItemBuilder.<init>(ItemBuilder.java:213) ~[oraxen-1.185.0.jar:?]
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.items.ItemBuilder.<init>(ItemBuilder.java:122) ~[oraxen-1.185.0.jar:?]
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:120) ~[oraxen-1.185.0.jar:?]
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:236) ~[oraxen-1.185.0.jar:?]
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:45) ~[oraxen-1.185.0.jar:?]
        at oraxen-1.185.0.jar/io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:108) ~[oraxen-1.185.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[slimeworldmanager-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[slimeworldmanager-1.20.6.jar:1.20.6-16004-7c72925]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[03:59:06 INFO]: [Oraxen] Disabling Oraxen v1.185.0
[03:59:06 INFO]: Oraxen | Successfully unloaded

### Steps to reproduce

Opened 1.20.6 paper server with oraxen

### Plugin Version

latest

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-736

### Server Software & Version

Advancedslimepaper 1.20.6
Paper 1.20.6

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Th0rgal** [comment]
Hello @Yiiitt , are you able to identify which item causes this error? It doesn't seem normal for default config generate via 1.183.0 : https://docs.oraxen.com/

**Comment by Yiiitt** [comment]
There are no items, everything is default, and when this error occurs, I can't even log into the server. When I remove the Oraxen jar, everything returns to normal.
